/*
 * This file is generated by jOOQ.
 */
package ch.v7.backend.persistence.tables.records


import ch.v7.backend.persistence.tables.RoleTable
import ch.v7.backend.persistence.tables.pojos.Role
import ch.v7.backend.role.Roles

import java.util.UUID

import org.jetbrains.annotations.NotNull
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class RoleRecord private constructor() : UpdatableRecordImpl<RoleRecord>(RoleTable.ROLE) {

    open var id: UUID
        set(value): Unit = set(0, value)
    @NotNull
        get(): UUID = get(0) as UUID

    open var name: Roles
        set(value): Unit = set(1, value)
    @NotNull
        get(): Roles = get(1) as Roles

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised RoleRecord
     */
    constructor(id: UUID, name: Roles): this() {
        this.id = id
        this.name = name
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised RoleRecord
     */
    constructor(value: Role?): this() {
        if (value != null) {
            this.id = value.id
            this.name = value.name
            resetChangedOnNotNull()
        }
    }
}
