/*
 * This file is generated by jOOQ.
 */
package ch.v7.backend.persistence.tables.records


import ch.v7.backend.persistence.tables.UserTable
import ch.v7.backend.persistence.tables.pojos.User

import java.util.UUID

import org.jetbrains.annotations.NotNull
import org.jetbrains.annotations.Nullable
import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record6
import org.jooq.Row6
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UserRecord private constructor() : UpdatableRecordImpl<UserRecord>(UserTable.USER), Record6<UUID?, String?, String?, String?, String?, String?> {

    open var id: UUID
        set(value): Unit = set(0, value)
    @NotNull
        get(): UUID = get(0) as UUID

    open var firstName: String
        set(value): Unit = set(1, value)
    @NotNull
        get(): String = get(1) as String

    open var lastName: String
        set(value): Unit = set(2, value)
    @NotNull
        get(): String = get(2) as String

    open var phone: String?
        set(value): Unit = set(3, value)
    @Nullable
        get(): String? = get(3) as String?

    open var eMail: String
        set(value): Unit = set(4, value)
    @NotNull
        get(): String = get(4) as String

    open var password: String
        set(value): Unit = set(5, value)
    @NotNull
        get(): String = get(5) as String

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row6<UUID?, String?, String?, String?, String?, String?> = super.fieldsRow() as Row6<UUID?, String?, String?, String?, String?, String?>
    override fun valuesRow(): Row6<UUID?, String?, String?, String?, String?, String?> = super.valuesRow() as Row6<UUID?, String?, String?, String?, String?, String?>
    override fun field1(): Field<UUID?> = UserTable.USER.ID
    override fun field2(): Field<String?> = UserTable.USER.FIRST_NAME
    override fun field3(): Field<String?> = UserTable.USER.LAST_NAME
    override fun field4(): Field<String?> = UserTable.USER.PHONE
    override fun field5(): Field<String?> = UserTable.USER.E_MAIL
    override fun field6(): Field<String?> = UserTable.USER.PASSWORD
    override fun component1(): UUID = id
    override fun component2(): String = firstName
    override fun component3(): String = lastName
    override fun component4(): String? = phone
    override fun component5(): String = eMail
    override fun component6(): String = password
    override fun value1(): UUID = id
    override fun value2(): String = firstName
    override fun value3(): String = lastName
    override fun value4(): String? = phone
    override fun value5(): String = eMail
    override fun value6(): String = password

    override fun value1(value: UUID?): UserRecord {
        set(0, value)
        return this
    }

    override fun value2(value: String?): UserRecord {
        set(1, value)
        return this
    }

    override fun value3(value: String?): UserRecord {
        set(2, value)
        return this
    }

    override fun value4(value: String?): UserRecord {
        set(3, value)
        return this
    }

    override fun value5(value: String?): UserRecord {
        set(4, value)
        return this
    }

    override fun value6(value: String?): UserRecord {
        set(5, value)
        return this
    }

    override fun values(value1: UUID?, value2: String?, value3: String?, value4: String?, value5: String?, value6: String?): UserRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        return this
    }

    /**
     * Create a detached, initialised UserRecord
     */
    constructor(id: UUID, firstName: String, lastName: String, phone: String? = null, eMail: String, password: String): this() {
        this.id = id
        this.firstName = firstName
        this.lastName = lastName
        this.phone = phone
        this.eMail = eMail
        this.password = password
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised UserRecord
     */
    constructor(value: User?): this() {
        if (value != null) {
            this.id = value.id
            this.firstName = value.firstName
            this.lastName = value.lastName
            this.phone = value.phone
            this.eMail = value.eMail
            this.password = value.password
            resetChangedOnNotNull()
        }
    }
}
