/*
 * This file is generated by jOOQ.
 */
package ch.v7.backend.persistence.tables.records


import ch.v7.backend.persistence.tables.UserRoleTable
import ch.v7.backend.persistence.tables.pojos.UserRole

import java.util.UUID

import org.jetbrains.annotations.NotNull
import org.jooq.Record2
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UserRoleRecord private constructor() : UpdatableRecordImpl<UserRoleRecord>(UserRoleTable.USER_ROLE) {

    open var userId: UUID
        set(value): Unit = set(0, value)
    @NotNull
        get(): UUID = get(0) as UUID

    open var roleId: UUID
        set(value): Unit = set(1, value)
    @NotNull
        get(): UUID = get(1) as UUID

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record2<UUID?, UUID?> = super.key() as Record2<UUID?, UUID?>

    /**
     * Create a detached, initialised UserRoleRecord
     */
    constructor(userId: UUID, roleId: UUID): this() {
        this.userId = userId
        this.roleId = roleId
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised UserRoleRecord
     */
    constructor(value: UserRole?): this() {
        if (value != null) {
            this.userId = value.userId
            this.roleId = value.roleId
            resetChangedOnNotNull()
        }
    }
}
