/*
 * This file is generated by jOOQ.
 */
package ch.v7.backend.persistence


import ch.v7.backend.persistence.tables.RessortTable
import ch.v7.backend.persistence.tables.RoleTable
import ch.v7.backend.persistence.tables.UserRessortTable
import ch.v7.backend.persistence.tables.UserRoleTable
import ch.v7.backend.persistence.tables.UserTable

import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Backend : SchemaImpl("backend", DefaultCatalog.DEFAULT_CATALOG) {
    public companion object {

        /**
         * The reference instance of <code>backend</code>
         */
        val BACKEND: Backend = Backend()
    }

    /**
     * The table <code>backend.t_ressort</code>.
     */
    val RESSORT: RessortTable get() = RessortTable.RESSORT

    /**
     * The table <code>backend.t_role</code>.
     */
    val ROLE: RoleTable get() = RoleTable.ROLE

    /**
     * The table <code>backend.t_user</code>.
     */
    val USER: UserTable get() = UserTable.USER

    /**
     * The table <code>backend.t_user_ressort</code>.
     */
    val USER_RESSORT: UserRessortTable get() = UserRessortTable.USER_RESSORT

    /**
     * The table <code>backend.t_user_role</code>.
     */
    val USER_ROLE: UserRoleTable get() = UserRoleTable.USER_ROLE

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        RessortTable.RESSORT,
        RoleTable.ROLE,
        UserTable.USER,
        UserRessortTable.USER_RESSORT,
        UserRoleTable.USER_ROLE
    )
}
