/*
 * This file is generated by jOOQ.
 */
package ch.v7.backend.persistence.tables.pojos


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class Ressort(
    val id: String,
    val name: String,
    val description: String? = null
): Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: Ressort = other as Ressort
        if (this.id != o.id)
            return false
        if (this.name != o.name)
            return false
        if (this.description == null) {
            if (o.description != null)
                return false
        }
        else if (this.description != o.description)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.id.hashCode()
        result = prime * result + this.name.hashCode()
        result = prime * result + (if (this.description == null) 0 else this.description.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Ressort (")

        sb.append(id)
        sb.append(", ").append(name)
        sb.append(", ").append(description)

        sb.append(")")
        return sb.toString()
    }
}
