/*
 * This file is generated by jOOQ.
 */
package ch.v7.backend.persistence.tables.pojos


import java.io.Serializable
import java.util.UUID


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class UserRole(
    val userId: UUID,
    val roleId: UUID
): Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: UserRole = other as UserRole
        if (this.userId != o.userId)
            return false
        if (this.roleId != o.roleId)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.userId.hashCode()
        result = prime * result + this.roleId.hashCode()
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("UserRole (")

        sb.append(userId)
        sb.append(", ").append(roleId)

        sb.append(")")
        return sb.toString()
    }
}
