/*
 * This file is generated by jOOQ.
 */
package ch.v7.backend.persistence.tables.pojos


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class User(
    val id: String,
    val firstName: String,
    val lastName: String,
    val phone: String? = null,
    val eMail: String,
    val userRole: String,
    val password: String
): Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: User = other as User
        if (this.id != o.id)
            return false
        if (this.firstName != o.firstName)
            return false
        if (this.lastName != o.lastName)
            return false
        if (this.phone == null) {
            if (o.phone != null)
                return false
        }
        else if (this.phone != o.phone)
            return false
        if (this.eMail != o.eMail)
            return false
        if (this.userRole != o.userRole)
            return false
        if (this.password != o.password)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.id.hashCode()
        result = prime * result + this.firstName.hashCode()
        result = prime * result + this.lastName.hashCode()
        result = prime * result + (if (this.phone == null) 0 else this.phone.hashCode())
        result = prime * result + this.eMail.hashCode()
        result = prime * result + this.userRole.hashCode()
        result = prime * result + this.password.hashCode()
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("User (")

        sb.append(id)
        sb.append(", ").append(firstName)
        sb.append(", ").append(lastName)
        sb.append(", ").append(phone)
        sb.append(", ").append(eMail)
        sb.append(", ").append(userRole)
        sb.append(", ").append(password)

        sb.append(")")
        return sb.toString()
    }
}
