/*
 * This file is generated by jOOQ.
 */
package ch.v7.backend.persistence.tables.references


import ch.v7.backend.persistence.tables.RessortTable
import ch.v7.backend.persistence.tables.UserRessortTable
import ch.v7.backend.persistence.tables.UserTable



/**
 * The table <code>backend.t_ressort</code>.
 */
val RESSORT: RessortTable = RessortTable.RESSORT

/**
 * The table <code>backend.t_user</code>.
 */
val USER: UserTable = UserTable.USER

/**
 * The table <code>backend.t_user_ressort</code>.
 */
val USER_RESSORT: UserRessortTable = UserRessortTable.USER_RESSORT
