/*
 * This file is generated by jOOQ.
 */
package ch.v7.backend.persistence.tables.references


import ch.v7.backend.persistence.tables.RessortTable
import ch.v7.backend.persistence.tables.RoleTable
import ch.v7.backend.persistence.tables.UserRessortTable
import ch.v7.backend.persistence.tables.UserRoleTable
import ch.v7.backend.persistence.tables.UserTable



/**
 * The table <code>v7_backend.t_ressort</code>.
 */
val RESSORT: RessortTable = RessortTable.RESSORT

/**
 * The table <code>v7_backend.t_role</code>.
 */
val ROLE: RoleTable = RoleTable.ROLE

/**
 * The table <code>v7_backend.t_user</code>.
 */
val USER: UserTable = UserTable.USER

/**
 * The table <code>v7_backend.t_user_ressort</code>.
 */
val USER_RESSORT: UserRessortTable = UserRessortTable.USER_RESSORT

/**
 * The table <code>v7_backend.t_user_role</code>.
 */
val USER_ROLE: UserRoleTable = UserRoleTable.USER_ROLE
